spring.application.name=BlogApp

# Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/blog_app_apis
spring.datasource.username=root
spring.datasource.password=root
# Optional: Specify the driver class name explicitly, though often not required with Spring Boot auto-detection
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA properties (if using JPA)
#spring.jpa.hibernate.ddl-auto=update # or create, create-drop, none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect